version: '2'
services:
  osmnames:
    build: .
    volumes:
      - .:/osmnames
      - ./data:${DATA_DIR}
    depends_on:
      - postgres
    env_file: .env

  postgres:
    image: mdillon/postgis:9.6
    environment:
      - POSTGRES_PASSWORD
