version: '3'
services:
  osmnames:
    build: .
    volumes:
      - .:/osmnames
    depends_on:
      - postgres
    volumes:
      - ./data:/osmnames/data/
    env_file: .env

  postgres:
    image: mdillon/postgis:9.6
    environment:
      - POSTGRES_PASSWORD
